name: FTP deploy
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 'ukrhat0.ftp.tools'
          username: 'ukrhat0_salary'
          password: 'v3d2GfZC77Bb'
